export const TUTORIAL_PRIMARY_ROW_ID = -999999;
export const TUTORIAL_SECONDARY_ROW_ID = -999998;
export const TUTORIAL_DONOR_OFFER_ID = -999997;

export const TUTORIAL_ITEM_ROW_ID = TUTORIAL_PRIMARY_ROW_ID;
export const TUTORIAL_ITEM_REQUEST_ID = TUTORIAL_SECONDARY_ROW_ID;

export const TUTORIAL_REQUEST_ROW_ID = TUTORIAL_PRIMARY_ROW_ID;
export const TUTORIAL_REQUEST_GENERAL_ITEM_ID = TUTORIAL_PRIMARY_ROW_ID;
export const TUTORIAL_REQUEST_DONOR_OFFER_ID = TUTORIAL_DONOR_OFFER_ID;

export const TUTORIAL_WISHLIST_ROW_ID = TUTORIAL_PRIMARY_ROW_ID;

export const TUTORIAL_DASHBOARD_COMPLETED_ROW_ID = TUTORIAL_PRIMARY_ROW_ID;
export const TUTORIAL_DASHBOARD_IN_PROGRESS_ROW_ID = TUTORIAL_SECONDARY_ROW_ID;
