import { FieldConfig } from "./FieldRenderer";

export const fieldConfigs: Record<string, FieldConfig[]> = {
  "General information": [
    {
      name: "siteName",
      label: "Site name",
      type: "text",
      required: true,
      placeholder: "Enter site name",
    },
    {
      name: "address",
      label: "Address",
      type: "location",
      required: true,
      placeholder: "Search for an address...",
    },
    {
      name: "department",
      label: "Department",
      type: "text",
      required: true,
      placeholder: "Enter department",
    },
    {
      name: "website",
      label: "Website",
      type: "text",
      placeholder: "Enter website URL",
    },
    {
      name: "socialMedia",
      label: "Social media (Instagram/Facebook)",
      type: "text",
      placeholder: "Enter social media links",
    },
  ],

  "Contact information": [
    {
      name: "regionalContact.firstName",
      label: "Regional Contact - First Name",
      type: "text",
      required: true,
    },
    {
      name: "regionalContact.lastName",
      label: "Regional Contact - Last Name",
      type: "text",
      required: true,
    },
    {
      name: "regionalContact.orgTitle",
      label: "Regional Contact - Organization Title",
      type: "text",
      required: true,
    },
    {
      name: "regionalContact.primaryTelephone",
      label: "Regional Contact - Primary Telephone",
      type: "text",
      required: true,
    },
    {
      name: "regionalContact.secondaryTelephone",
      label: "Regional Contact - Secondary Telephone",
      type: "text",
    },
    {
      name: "regionalContact.email",
      label: "Regional Contact - Email",
      type: "email",
      required: true,
    },
    {
      name: "medicalContact.firstName",
      label: "Medical Contact - First Name",
      type: "text",
      required: true,
    },
    {
      name: "medicalContact.lastName",
      label: "Medical Contact - Last Name",
      type: "text",
      required: true,
    },
    {
      name: "medicalContact.orgTitle",
      label: "Medical Contact - Organization Title",
      type: "text",
      required: true,
    },
    {
      name: "medicalContact.primaryTelephone",
      label: "Medical Contact - Primary Telephone",
      type: "text",
      required: true,
    },
    {
      name: "medicalContact.secondaryTelephone",
      label: "Medical Contact - Secondary Telephone",
      type: "text",
    },
    {
      name: "medicalContact.email",
      label: "Medical Contact - Email",
      type: "email",
      required: true,
    },
    {
      name: "adminDirectorContact.firstName",
      label: "Admin Director - First Name",
      type: "text",
      required: true,
    },
    {
      name: "adminDirectorContact.lastName",
      label: "Admin Director - Last Name",
      type: "text",
      required: true,
    },
    {
      name: "adminDirectorContact.orgTitle",
      label: "Admin Director - Organization Title",
      type: "text",
      required: true,
    },
    {
      name: "adminDirectorContact.primaryTelephone",
      label: "Admin Director - Primary Telephone",
      type: "text",
      required: true,
    },
    {
      name: "adminDirectorContact.secondaryTelephone",
      label: "Admin Director - Secondary Telephone",
      type: "text",
    },
    {
      name: "adminDirectorContact.email",
      label: "Admin Director - Email",
      type: "email",
      required: true,
    },
    {
      name: "pharmacyContact.firstName",
      label: "Pharmacy Contact - First Name",
      type: "text",
      required: true,
    },
    {
      name: "pharmacyContact.lastName",
      label: "Pharmacy Contact - Last Name",
      type: "text",
      required: true,
    },
    {
      name: "pharmacyContact.orgTitle",
      label: "Pharmacy Contact - Organization Title",
      type: "text",
      required: true,
    },
    {
      name: "pharmacyContact.primaryTelephone",
      label: "Pharmacy Contact - Primary Telephone",
      type: "text",
      required: true,
    },
    {
      name: "pharmacyContact.secondaryTelephone",
      label: "Pharmacy Contact - Secondary Telephone",
      type: "text",
    },
    {
      name: "pharmacyContact.email",
      label: "Pharmacy Contact - Email",
      type: "email",
      required: true,
    },
    {
      name: "contactWhatsAppName",
      label: "WhatsApp Contact Name",
      type: "text",
    },
    {
      name: "contactWhatsAppNumber",
      label: "WhatsApp Contact Number",
      type: "text",
    },
  ],

  Introduction: [
    {
      name: "organizationHistory",
      label: "Organization history",
      type: "textarea",
      required: true,
      placeholder: "Describe the organization's history",
    },
    {
      name: "supportRequested",
      label: "Type of support requested",
      type: "select",
      required: true,
      options: [
        { value: "ongoing_support", label: "Ongoing Support" },
        { value: "mobile_clinic_support", label: "Mobile Clinic Support" },
        { value: "one_time_request", label: "One Time Request" },
        { value: "project_support", label: "Project Support" },
      ],
    },
    {
      name: "yearOrganizationEstablished",
      label: "Year organization was established",
      type: "number",
      required: true,
      min: 1800,
      max: new Date().getFullYear(),
    },
    {
      name: "registeredWithMssp",
      label: "Registered with MSSP",
      type: "boolean",
      required: true,
    },
    {
      name: "proofOfRegistrationWithMssp",
      label: "Proof of registration with MSSP",
      type: "file",
      conditionalField: "registeredWithMssp",
      conditionalValue: true,
      accept: ".pdf,.doc,.docx,.jpg,.jpeg,.png",
      description: "Upload proof of registration document",
    },
    {
      name: "programUpdatesSinceLastReport",
      label: "Program updates since last report",
      type: "textarea",
      placeholder: "Describe any program updates",
    },
  ],

  "Facility Information": [
    {
      name: "facilityType",
      label: "What type of facility is it? (Select all that apply)",
      type: "multiselect",
      required: true,
      options: [
        { value: "birthing_center", label: "Birthing Center" },
        { value: "clinic", label: "Clinic" },
        { value: "hospital", label: "Hospital" },
        { value: "elderly_care", label: "Elderly Care" },
        { value: "rehabilitation_center", label: "Rehabilitation Center" },
        { value: "dispensary", label: "Dispensary" },
        { value: "orphanage", label: "Orphanage" },
        { value: "primary_care", label: "Primary Care" },
        { value: "health_center", label: "Health Center" },
        {
          value: "community_health_education",
          label: "Community Health Education",
        },
        { value: "nutrition_feeding", label: "Nutrition/Feeding" },
        {
          value: "secondary_tertiary_healthcare",
          label: "Secondary/Tertiary Healthcare",
        },
      ],
    },
    {
      name: "organizationType",
      label: "Organization type (Select all that apply)",
      type: "multiselect",
      required: true,
      options: [
        { value: "non_profit", label: "Non-profit" },
        { value: "for_profit", label: "For Profit" },
        { value: "faith_based", label: "Faith-based" },
      ],
    },
    {
      name: "governmentRun",
      label: "Is this a government-run organization?",
      type: "boolean",
      required: true,
    },
    {
      name: "emergencyMedicalRecordsSystemPresent",
      label: "Do you have an Emergency Medical Records (EMR) System?",
      type: "boolean",
      required: true,
    },
    {
      name: "emergencyMedicalRecordsSystemName",
      label: "EMR System Name",
      type: "text",
      conditionalField: "emergencyMedicalRecordsSystemPresent",
      conditionalValue: true,
      placeholder: "Enter EMR system name",
    },
    {
      name: "numberOfInpatientBeds",
      label: "Number of inpatient beds",
      type: "number",
      min: 0,
    },
    {
      name: "numberOfPatientsServedAnnually",
      label: "Number of patients served annually",
      type: "number",
      min: 0,
    },
    {
      name: "communityMobileOutreachOffered",
      label: "Do you offer community/mobile outreach?",
      type: "boolean",
      required: true,
    },
    {
      name: "communityMobileOutreachDescription",
      label: "Community/mobile outreach description",
      type: "textarea",
      conditionalField: "communityMobileOutreachOffered",
      conditionalValue: true,
      placeholder: "Describe how often and what services are offered",
    },
  ],

  "Infrastructure & Services": [
    {
      name: "facilityDescription",
      label: "Facility description",
      type: "textarea",
      placeholder: "Describe your facility",
    },
    {
      name: "cleanWaterAccessible",
      label: "Is clean water accessible?",
      type: "boolean",
      required: true,
    },
    {
      name: "cleanWaterDescription",
      label: "Clean water description",
      type: "textarea",
      conditionalField: "cleanWaterAccessible",
      conditionalValue: true,
      placeholder: "Describe the accessible clean water",
    },
    {
      name: "closestSourceOfCleanWater",
      label: "Closest source of clean water",
      type: "text",
      conditionalField: "cleanWaterAccessible",
      conditionalValue: false,
      placeholder: "Describe the closest source of clean water",
    },
    {
      name: "sanitationFacilitiesPresent",
      label: "Are sanitation facilities present?",
      type: "boolean",
      required: true,
    },
    {
      name: "sanitationFacilitiesLockableFromInside",
      label: "Are sanitation facilities lockable from inside?",
      type: "boolean",
      conditionalField: "sanitationFacilitiesPresent",
      conditionalValue: true,
    },
    {
      name: "electricityAvailable",
      label: "Is electricity available?",
      type: "boolean",
      required: true,
    },
    {
      name: "accessibleByDisablePatients",
      label: "Is the facility accessible by disabled patients?",
      type: "boolean",
      required: true,
    },
    {
      name: "medicationDisposalProcessDefined",
      label: "Is medication disposal process defined?",
      type: "boolean",
      required: true,
    },
    {
      name: "medicationDisposalProcessDescription",
      label: "Medication disposal process description",
      type: "textarea",
      conditionalField: "medicationDisposalProcessDefined",
      conditionalValue: true,
      placeholder: "Describe the medication disposal process",
    },
    {
      name: "pickupVehiclePresent",
      label: "Is pickup vehicle present?",
      type: "boolean",
      required: true,
    },
    {
      name: "pickupVehicleType",
      label: "Pickup vehicle type",
      type: "text",
      conditionalField: "pickupVehiclePresent",
      conditionalValue: true,
      placeholder: "Describe the pickup vehicle type",
    },
    {
      name: "pickupLocations",
      label: "Pickup locations",
      type: "multiselect",
      conditionalField: "pickupVehiclePresent",
      conditionalValue: true,
      options: [
        { value: "les_cayes", label: "Les Cayes" },
        { value: "port_au_prince", label: "Port-au-Prince" },
      ],
    },
  ],

  "Programs & Services Provided": [
    {
      name: "medicalServicesProvided",
      label: "Medical services provided (Select all that apply)",
      type: "multiselect",
      required: true,
      options: [
        { value: "cancer", label: "Cancer" },
        { value: "dentistry", label: "Dentistry" },
        { value: "dermatology", label: "Dermatology" },
        { value: "hematology", label: "Hematology" },
        { value: "immunizations", label: "Immunizations" },
        { value: "parasitic_infections", label: "Parasitic Infections" },
        {
          value: "acute_respiratory_infections",
          label: "Acute Respiratory Infections",
        },
        { value: "vector_borne_diseases", label: "Vector Borne Diseases" },
        { value: "chronic_diseases", label: "Chronic Diseases" },
        { value: "diarrheal_diseases", label: "Diarrheal Diseases" },
        {
          value: "vaccine_preventable_diseases",
          label: "Vaccine Preventable Diseases",
        },
        { value: "infectious_diseases", label: "Infectious Diseases" },
        { value: "neurology", label: "Neurology" },
        { value: "malnutrition", label: "Malnutrition" },
        { value: "ophthalmology", label: "Ophthalmology" },
        { value: "ears_nose_throat", label: "Ears, Nose & Throat" },
        {
          value: "orthopedics_and_rehabilitation",
          label: "Orthopedics and Rehabilitation",
        },
        { value: "pediatrics", label: "Pediatrics" },
        { value: "radiology", label: "Radiology" },
        { value: "wound_care", label: "Wound Care" },
        { value: "maternal_care", label: "Maternal Care" },
        { value: "lab_tests", label: "Lab Tests" },
        { value: "trauma_and_surgery", label: "Trauma and Surgery" },
        { value: "urology", label: "Urology" },
      ],
    },
    {
      name: "otherMedicalServicesProvided",
      label: "Other medical services provided",
      type: "textarea",
      placeholder: "Describe any other medical services provided",
    },
    {
      name: "mostNeededMedicalSupplies",
      label: "Most needed medical supplies (Select all that apply)",
      type: "multiselect",
      options: [
        { value: "anesthetics", label: "Anesthetics" },
        { value: "antipyretics_nsaids", label: "Antipyretics/NSAIDs" },
        { value: "antiallergics", label: "Antiallergics" },
        { value: "anti_infectives", label: "Anti-infectives" },
        { value: "antineoplastics", label: "Antineoplastics" },
        { value: "cardiovascular", label: "Cardiovascular" },
        { value: "dermatological", label: "Dermatological" },
        { value: "diagnostics", label: "Diagnostics" },
        { value: "diuretics", label: "Diuretics" },
        { value: "gastrointestinal", label: "Gastrointestinal" },
        { value: "ophthalmological", label: "Ophthalmological" },
        { value: "respiratory", label: "Respiratory" },
        { value: "replacements", label: "Replacements" },
        { value: "vitamins_minerals", label: "Vitamins & Minerals" },
        { value: "bandages", label: "Bandages" },
        { value: "braces", label: "Braces" },
        { value: "hospital_consumables", label: "Hospital Consumables" },
        { value: "dental", label: "Dental" },
        { value: "diagnostic", label: "Diagnostic" },
        { value: "personal_care", label: "Personal Care" },
        { value: "Prosthetics", label: "Prosthetics" },
        { value: "surgical", label: "Surgical" },
        { value: "syringes_needles", label: "Syringes & Needles" },
      ],
    },
    {
      name: "otherSpecialityItemsNeeded",
      label: "Other specialty items needed",
      type: "textarea",
      placeholder: "Describe any other specialty items needed",
    },
  ],

  Finances: [
    {
      name: "patientsWhoCannotPay",
      label: "Patients who cannot pay",
      type: "textarea",
      placeholder: "Describe how you handle patients who cannot pay",
    },
    {
      name: "percentageOfPatientsNeedingFinancialAid",
      label: "Percentage of patients needing financial aid",
      type: "number",
      min: 0,
      max: 100,
    },
    {
      name: "percentageOfPatientsReceivingFreeTreatment",
      label: "Percentage of patients receiving free treatment",
      type: "number",
      min: 0,
      max: 100,
    },
    {
      name: "annualSpendingOnMedicationsAndMedicalSupplies",
      label: "Annual spending on medications and medical supplies",
      type: "select",
      required: true,
      options: [
        { value: "1_to_5000", label: "$1 - $5,000" },
        { value: "5001_to_10000", label: "$5,001 - $10,000" },
        { value: "10001_to_25000", label: "$10,001 - $25,000" },
        { value: "25001_to_50000", label: "$25,001 - $50,000" },
        { value: "50001_to_100000", label: "$50,001 - $100,000" },
        { value: "100001+", label: "$100,001+" },
      ],
    },
    {
      name: "numberOfPrescriptionsPrescribedAnnuallyTracked",
      label: "Do you track the number of prescriptions prescribed annually?",
      type: "boolean",
      required: true,
    },
    {
      name: "numberOfTreatmentsPrescribedAnnually",
      label: "Number of treatments prescribed annually",
      type: "number",
      min: 0,
    },
    {
      name: "anyMenServedLastYear",
      label: "Were any men (18+) served last year?",
      type: "boolean",
      required: true,
    },
    {
      name: "menServedLastYear",
      label: "Number of men (18+) served last year",
      type: "number",
      conditionalField: "anyMenServedLastYear",
      conditionalValue: true,
      min: 0,
    },
    {
      name: "anyWomenServedLastYear",
      label: "Were any women (18+) served last year?",
      type: "boolean",
      required: true,
    },
    {
      name: "womenServedLastYear",
      label: "Number of women (18+) served last year",
      type: "number",
      conditionalField: "anyWomenServedLastYear",
      conditionalValue: true,
      min: 0,
    },
    {
      name: "anyBoysServedLastYear",
      label: "Were any boys (1-17) served last year?",
      type: "boolean",
      required: true,
    },
    {
      name: "boysServedLastYear",
      label: "Number of boys (1-17) served last year",
      type: "number",
      conditionalField: "anyBoysServedLastYear",
      conditionalValue: true,
      min: 0,
    },
    {
      name: "anyGirlsServedLastYear",
      label: "Were any girls (1-17) served last year?",
      type: "boolean",
      required: true,
    },
    {
      name: "girlsServedLastYear",
      label: "Number of girls (1-17) served last year",
      type: "number",
      conditionalField: "anyGirlsServedLastYear",
      conditionalValue: true,
      min: 0,
    },
    {
      name: "anyBabyBoysServedLastYear",
      label: "Were any baby boys (<1) served last year?",
      type: "boolean",
      required: true,
    },
    {
      name: "babyBoysServedLastYear",
      label: "Number of baby boys (<1) served last year",
      type: "number",
      conditionalField: "anyBabyBoysServedLastYear",
      conditionalValue: true,
      min: 0,
    },
    {
      name: "anyBabyGirlsServedLastYear",
      label: "Were any baby girls (<1) served last year?",
      type: "boolean",
      required: true,
    },
    {
      name: "babyGirlsServedLastYear",
      label: "Number of baby girls (<1) served last year",
      type: "number",
      conditionalField: "anyBabyGirlsServedLastYear",
      conditionalValue: true,
      min: 0,
    },
    {
      name: "totalPatientsServedLastYear",
      label: "Total patients served last year",
      type: "number",
      min: 0,
    },
  ],

  "Staff Information": [
    {
      name: "numberOfDoctors",
      label: "Number of doctors",
      type: "number",
      min: 0,
    },
    {
      name: "numberOfNurses",
      label: "Number of nurses",
      type: "number",
      min: 0,
    },
    {
      name: "numberOfMidwives",
      label: "Number of midwives",
      type: "number",
      min: 0,
    },
    {
      name: "numberOfAuxilaries",
      label: "Number of auxiliaries",
      type: "number",
      min: 0,
    },
    {
      name: "numberOfStatisticians",
      label: "Number of statisticians",
      type: "number",
      min: 0,
    },
    {
      name: "numberOfPharmacists",
      label: "Number of pharmacists",
      type: "number",
      min: 0,
    },
    {
      name: "numberOfCHW",
      label: "Number of Community Health Workers (CHW)",
      type: "number",
      min: 0,
    },
    {
      name: "numberOfAdministrative",
      label: "Number of administrative staff",
      type: "number",
      min: 0,
    },
    {
      name: "numberOfHealthOfficers",
      label: "Number of health officers",
      type: "number",
      min: 0,
    },
    {
      name: "totalNumberOfStaff",
      label: "Total number of staff",
      type: "number",
      min: 0,
    },
    {
      name: "other",
      label: "Other staff information",
      type: "textarea",
      placeholder: "Describe any other staff information",
    },
  ],
};

// Tab order for consistent navigation
export const tabOrder = [
  "General information",
  "Contact information",
  "Introduction",
  "Facility Information",
  "Infrastructure & Services",
  "Programs & Services Provided",
  "Finances",
  "Staff Information",
];

// Step-specific field configurations for CreatePartnerAccount
export const stepFieldConfigs: Record<number, FieldConfig[]> = {
  1: fieldConfigs["General information"],

  2: fieldConfigs["Contact information"],

  3: fieldConfigs["Introduction"],

  4: fieldConfigs["Facility Information"],

  5: fieldConfigs["Infrastructure & Services"],

  6: [
    // Only the medical services part of Programs & Services
    {
      name: "medicalServicesProvided",
      label: "Medical services provided (Select all that apply)",
      type: "multiselect",
      required: true,
      options: [
        { value: "cancer", label: "Cancer" },
        { value: "dentistry", label: "Dentistry" },
        { value: "dermatology", label: "Dermatology" },
        { value: "hematology", label: "Hematology" },
        { value: "immunizations", label: "Immunizations" },
        { value: "parasitic_infections", label: "Parasitic Infections" },
        {
          value: "acute_respiratory_infections",
          label: "Acute Respiratory Infections",
        },
        { value: "vector_borne_diseases", label: "Vector Borne Diseases" },
        { value: "chronic_diseases", label: "Chronic Diseases" },
        { value: "diarrheal_diseases", label: "Diarrheal Diseases" },
        {
          value: "vaccine_preventable_diseases",
          label: "Vaccine Preventable Diseases",
        },
        { value: "infectious_diseases", label: "Infectious Diseases" },
        { value: "neurology", label: "Neurology" },
        { value: "malnutrition", label: "Malnutrition" },
        { value: "ophthalmology", label: "Ophthalmology" },
        { value: "ears_nose_throat", label: "Ears, Nose & Throat" },
        {
          value: "orthopedics_and_rehabilitation",
          label: "Orthopedics and Rehabilitation",
        },
        { value: "pediatrics", label: "Pediatrics" },
        { value: "radiology", label: "Radiology" },
        { value: "wound_care", label: "Wound Care" },
        { value: "maternal_care", label: "Maternal Care" },
        { value: "lab_tests", label: "Lab Tests" },
        { value: "trauma_and_surgery", label: "Trauma and Surgery" },
        { value: "urology", label: "Urology" },
      ],
    },
    {
      name: "otherMedicalServicesProvided",
      label: "Other medical services provided",
      type: "textarea",
      placeholder: "Describe any other medical services provided",
    },
  ],

  7: [
    // First part of finances
    {
      name: "patientsWhoCannotPay",
      label: "Patients who cannot pay",
      type: "textarea",
      placeholder: "Describe how you handle patients who cannot pay",
    },
    {
      name: "percentageOfPatientsNeedingFinancialAid",
      label: "Percentage of patients needing financial aid",
      type: "number",
      min: 0,
      max: 100,
    },
    {
      name: "percentageOfPatientsReceivingFreeTreatment",
      label: "Percentage of patients receiving free treatment",
      type: "number",
      min: 0,
      max: 100,
    },
    {
      name: "annualSpendingOnMedicationsAndMedicalSupplies",
      label: "Annual spending on medications and medical supplies",
      type: "select",
      required: true,
      options: [
        { value: "1_to_5000", label: "$1 - $5,000" },
        { value: "5001_to_10000", label: "$5,001 - $10,000" },
        { value: "10001_to_25000", label: "$10,001 - $25,000" },
        { value: "25001_to_50000", label: "$25,001 - $50,000" },
        { value: "50001_to_100000", label: "$50,001 - $100,000" },
        { value: "100001+", label: "$100,001+" },
      ],
    },
    {
      name: "numberOfPrescriptionsPrescribedAnnuallyTracked",
      label: "Do you track the number of prescriptions prescribed annually?",
      type: "boolean",
      required: true,
    },
    {
      name: "numberOfTreatmentsPrescribedAnnually",
      label: "Number of treatments prescribed annually",
      type: "number",
      min: 0,
    },
  ],

  8: [
    // Second part of finances - patient demographics
    {
      name: "anyMenServedLastYear",
      label: "Were any men (18+) served last year?",
      type: "boolean",
      required: true,
    },
    {
      name: "menServedLastYear",
      label: "Number of men (18+) served last year",
      type: "number",
      conditionalField: "anyMenServedLastYear",
      conditionalValue: true,
      min: 0,
    },
    {
      name: "anyWomenServedLastYear",
      label: "Were any women (18+) served last year?",
      type: "boolean",
      required: true,
    },
    {
      name: "womenServedLastYear",
      label: "Number of women (18+) served last year",
      type: "number",
      conditionalField: "anyWomenServedLastYear",
      conditionalValue: true,
      min: 0,
    },
    {
      name: "anyBoysServedLastYear",
      label: "Were any boys (1-17) served last year?",
      type: "boolean",
      required: true,
    },
    {
      name: "boysServedLastYear",
      label: "Number of boys (1-17) served last year",
      type: "number",
      conditionalField: "anyBoysServedLastYear",
      conditionalValue: true,
      min: 0,
    },
    {
      name: "anyGirlsServedLastYear",
      label: "Were any girls (1-17) served last year?",
      type: "boolean",
      required: true,
    },
    {
      name: "girlsServedLastYear",
      label: "Number of girls (1-17) served last year",
      type: "number",
      conditionalField: "anyGirlsServedLastYear",
      conditionalValue: true,
      min: 0,
    },
    {
      name: "anyBabyBoysServedLastYear",
      label: "Were any baby boys (<1) served last year?",
      type: "boolean",
      required: true,
    },
    {
      name: "babyBoysServedLastYear",
      label: "Number of baby boys (<1) served last year",
      type: "number",
      conditionalField: "anyBabyBoysServedLastYear",
      conditionalValue: true,
      min: 0,
    },
    {
      name: "anyBabyGirlsServedLastYear",
      label: "Were any baby girls (<1) served last year?",
      type: "boolean",
      required: true,
    },
    {
      name: "babyGirlsServedLastYear",
      label: "Number of baby girls (<1) served last year",
      type: "number",
      conditionalField: "anyBabyGirlsServedLastYear",
      conditionalValue: true,
      min: 0,
    },
    {
      name: "totalPatientsServedLastYear",
      label: "Total patients served last year",
      type: "number",
      min: 0,
    },
  ],

  9: fieldConfigs["Staff Information"],

  10: [
    // Medical supplies section
    {
      name: "mostNeededMedicalSupplies",
      label: "Most needed medical supplies (Select all that apply)",
      type: "multiselect",
      options: [
        { value: "anesthetics", label: "Anesthetics" },
        { value: "antipyretics_nsaids", label: "Antipyretics/NSAIDs" },
        { value: "antiallergics", label: "Antiallergics" },
        { value: "anti_infectives", label: "Anti-infectives" },
        { value: "antineoplastics", label: "Antineoplastics" },
        { value: "cardiovascular", label: "Cardiovascular" },
        { value: "dermatological", label: "Dermatological" },
        { value: "diagnostics", label: "Diagnostics" },
        { value: "diuretics", label: "Diuretics" },
        { value: "gastrointestinal", label: "Gastrointestinal" },
        { value: "ophthalmological", label: "Ophthalmological" },
        { value: "respiratory", label: "Respiratory" },
        { value: "replacements", label: "Replacements" },
        { value: "vitamins_minerals", label: "Vitamins & Minerals" },
        { value: "bandages", label: "Bandages" },
        { value: "braces", label: "Braces" },
        { value: "hospital_consumables", label: "Hospital Consumables" },
        { value: "dental", label: "Dental" },
        { value: "diagnostic", label: "Diagnostic" },
        { value: "personal_care", label: "Personal Care" },
        { value: "Prosthetics", label: "Prosthetics" },
        { value: "surgical", label: "Surgical" },
        { value: "syringes_needles", label: "Syringes & Needles" },
      ],
    },
    {
      name: "otherSpecialityItemsNeeded",
      label: "Other specialty items needed",
      type: "textarea",
      placeholder: "Describe any other specialty items needed",
    },
  ],
};
